### PR TITLE
TRE-105 Added JsonSerializingWebSocket.messages

### PR DESCRIPTION
**Pull request by VishnuSubramanianTrenser**
…erver to customize response send to server

### CODE REVIEW

**Review by zvi-quantivly — APPROVED** [review]

**Review by zvi-quantivly — APPROVED** [review]
Looks OK at a very high level, but not sure I fully understand the where this information is used (e.g., where is `ack_messages` read?).

**Comment by VishnuSubramanianTrenser** [comment]
> Looks OK at a very high level, but not sure I fully understand the where this information is used (e.g., where is `ack_messages` read?).

Yes, not only to read **ack_messages** but also to hold all **request_messages** from server. This is because on every procedure call the **recv()** co-routine hold only the current message. As we are triggering sending chunk messages after the **gettattr** get invoked we will lost the request data. That's why added the logic here.

**Comment by zvi-quantivly** [comment]
@VishnuSubramanianTrenser, can this be merged?

**Comment by VishnuSubramanianTrenser** [comment]
> @VishnuSubramanianTrenser, can this be merged?

Yes @zvi-quantivly, could you please merge it? I have no privilege to merge it.

**Pull request merged**
